### ISSUE TITLE
Your app contains exposed Google Cloud Platform (GCP) API keys

### ISSUE THREAD

**Issue by DurgaArunkumarSmitiv** [googlemaps/android-places-demos#29] opened 2019-09-17 04:25 UTC
Your app contains exposed Google Cloud Platform (GCP) API keys, the Classes:
MainActivity->onCreate

Please refer to the following article on how to fix the issue:
https://support.google.com/faqs/answer/9287711

I am getting this alert from my google play store console.  I have added restrictions to my apikey. but i have used same line as demo

**String apiKey = getResources().getString(R.string.google_api_key);

if (!Places.isInitialized()) {
    Places.initialize(getApplicationContext(), apiKey);
}**

this is cause of this issue. How to rectify this. Can you please explain

**Comment by jpoehnelt** [comment] 2019-09-18 18:43
@DurgaArunkumarSmitiv I'll try to take a look at this but you may get a faster response on StackOverflow with tag `google-maps`. See here for more information: https://developers.google.com/maps/documentation/android-sdk/get-api-key#key-std-details

**Comment by abhishekthanvi8** [comment] 2019-11-26 11:07
Did you have any solution for this issue?

**Comment by arriolac** [comment] 2020-02-18 19:24
HI @DurgaArunkumarSmitiv what method did you use to include the API key in your app? Did you add the API key via `gradle.properties` (which will autogenerate an entry in .xml) or are you storing the API key in .xml directly?

**Comment by 20ali20** [comment] 2020-02-28 06:04
@arriolac 
I get the same issue and I have implemented my keys via gradle.properties which is the safe way. I believe because its actually called google_maps_key somehow that triggers the warning which is not a wise method for detecting flaws in the app.

**Comment by DurgaArunkumarSmitiv** [comment] 2020-02-28 06:28
Hi
   Yes even from gradle faced same issue. Getting the keys from server
helped me.

*Regards*
*Durga*
*Android Developer*

**Comment by arriolac** [comment] 2020-03-03 18:18
I can confirm that the warning shows even with the build time `gradle.properties` key/value property approach (see instructions [here](https://developer.android.com/studio/build/gradle-tips#share-custom-fields-and-resource-values-with-your-app-code)). While this approach is certainly better than storing the API key in source control, please refer to our [API key best practices](https://cloud.google.com/docs/authentication/api-keys#securing_an_api_key) to ensure your API key is absolutely secure. To remove the warning itself from the Play Console, you'll have to completely remove the API from your code (@DurgaArunkumarSmitiv approach works or you can store an encrypted version of the API key in code).

**Comment by tallinn1960** [comment] 2020-03-18 19:07
Today while uploading a repo I got a warning about an MAPS API key that I replaced already back in January. Why is that? I can't remove it from the repo as it is part of very old commits only in files long since heavily modified and replaced/moved, with the key removed from themin the process..

**Comment by therafaelreis** [comment] 2020-05-26 16:26
I am having the same issue, I put the key in a property file, and reading that file in the gradle, but that key will be in BuildConfig.java once it's generate, and that is what is complaining about it, I am not sure if is truly a problem or just like false-positive.
Did anyone find a solution to this issue?

**Comment by MohammedShehata** [comment] 2020-06-08 10:44
@DurgaArunkumarSmitiv did you have a solution for this problem ?
Thanks!

**Comment by arriolac** [comment] 2020-06-30 22:17
The warning in the Play Console can be safely ignored assuming the best practices outlined in [Securing an API key](https://cloud.google.com/docs/authentication/api-keys#securing_an_api_key) are applied. Specifically, make sure to apply [API key restrictions](https://cloud.google.com/docs/authentication/api-keys#api_key_restrictions) and ensure that the API key is not checked into source code (see PR #78 as an example for how to do this).

**Comment by arriolac** [comment] 2020-07-08 20:09
Our FAQ page for [Remediation for Exposed GCP API keys](https://support.google.com/faqs/answer/9287711) has been updated to reflect that the warning can be safely ignored.

> Add restrictions to your API key so that only your apps are allowed to use the API key. More details on adding restrictions to API keys can be found [here](https://cloud.google.com/docs/authentication/api-keys#api_key_restrictions). (Please Note: If you have already added restrictions to your API key, you can ignore this warning.)

**Closed by arriolac** 2020-07-08 20:09 UTC
Labels: status: investigating, type: question

**Comment by tallinn1960** [comment] 2020-07-10 09:23
Please note that this does not resolve the problem I reported here: a warning about publishing an API key that I replaced in GCP console with an unpublished one already.

**Comment by milanmaji** [comment] 2022-02-17 18:03
I also faced the same problem. I couldn't find any proper solution for this. After lot of searching I found a solution. So I am giving a complete guide for this issue.
Link : https://stackoverflow.com/a/71155071/13387867

**Comment by DarshanSavaliyaGitHub** [comment] 2024-04-22 11:08
I'm also facing the same problem, with the play console.
