### ISSUE TITLE
Compat - PlacePicker closes immediately after launch

### ISSUE THREAD

**Issue by CyanDeveloper** [googlemaps/android-places-demos#2] opened 2019-02-05 09:25 UTC
By installing the demo app ther is an issue on **PlacePicker**.
**CurrentPlace** and **AutoComplete** features works correctly but PP is shown and closed immediately without errors or warnings.
It can't be a API Key issue because 2/3 features works perfectly showing data.

**Comment by cr05s19xx** [comment] 2019-02-17 15:50
Same issue here

**Comment by amuramoto** [comment] 2019-02-19 17:02
@CyanDeveloper @cr05s19xx Can you provide error logs? I just tested this on API 25, 26, 27, and 28 with no issue

**Comment by CyanDeveloper** [comment] 2019-02-19 17:04
> 
> 
> @CyanDeveloper @cr05s19xx Can you provide error logs? I just tested this on API 25, 26, 27, and 28 with no issue

No error.. it closes immediatly like "permission denied" issue.. but if I change it with Compat AutoComplete all works well. So, it isn't permissions problem.

**Comment by amuramoto** [comment] 2019-02-19 17:20
What API version are you using?

**Comment by CyanDeveloper** [comment] 2019-02-19 17:24
I run it on Samsung S7 with Android 8.0.0
The project was cloned and not modified.

**Comment by amuramoto** [comment] 2019-02-19 19:43
There's no crash log in Logcat when this happens? Can you try testing on a more recent API version as well? Would like to see if this is specific to the API version + device or not. I've run this with Android 8.0.0 on a Pixel 2 and it ran without issue.

**Comment by CyanDeveloper** [comment] 2019-02-19 19:48
> 
> 
> There's no crash log in Logcat when this happens? Can you try testing on a more recent API version as well? Would like to see if this is specific to the API version + device or not. I've run this with Android 8.0.0 on a Pixel 2 and it ran without issue.

@amuramoto ... No log, no crash.. simply closes PP activity returning to MainActivity that show the options to pick a place (PlacePicker, AutoComplete and PlacePhotos)..

Is the same behavior as an api error, but without errors.. it close activity immediatly.

Anyway, I'll try run it on an emulated device and another physical device, letting you know if works or not.

**Comment by amuramoto** [comment] 2019-02-19 20:17
Ok thanks - I'm not able to reproduce the error, so it is difficult to help debug at this point

**Comment by cr05s19xx** [comment] 2019-02-19 20:19
There **is** an error being thrown, but my biggest suspect is this error:

https://stackoverflow.com/questions/30067210/android-place-picker-closes-immediately-after-launch...

I'm not sure why this is happening, especially since the other components work perfectly

**Comment by amuramoto** [comment] 2019-02-20 06:05
@cr05s19xx Can you share the error being thrown?

I don't think the SO issue you pointed to is the root cause (at least not in all cases) since I am able to run the sample without the described behavior.

**Comment by strangelove11** [comment] 2019-02-23 23:52
Same issue

**Comment by gavingt** [comment] 2019-02-27 05:42
With the new SDK, the PlacePicker will only work for API keys that were activated prior to the PlacePicker's deprecation date (January 29, 2019). Or, at least, that's how I interpret the email Google sent me:

> Effective January 29, 2019, the upgraded Places SDKs for Android and iOS will replace the existing versions of the Places SDKs - please read our documentation for more information. The existing Places SDKs (including the Place Picker feature) can continue being used by current customers of these SDKs until July 29, 2019. In order to avoid service disruption, please start using the upgraded SDK versions before July 29, 2019.

**Comment by CyanDeveloper** [comment] 2019-02-27 10:58
> 
> 
> With the new SDK, the PlacePicker will only work for API keys that were activated prior to the PlacePicker's deprecation date (January 29, 2019). Or, at least, that's how I interpret the email Google sent me when they announced the new SDK:
> 
> > Effective January 29, 2019, the upgraded Places SDKs for Android and iOS will replace the existing versions of the Places SDKs - please read our documentation for more information. The existing Places SDKs (including the Place Picker feature) can continue being used by current customers of these SDKs until July 29, 2019. In order to avoid service disruption, please start using the upgraded SDK versions before July 29, 2019.
> 
> So the PlacePicker might not be working for some people while other features do, simply because your API key isn't flagged to use the PlacePicker through the deprecation period.

This is not true. You have misinterpreted the text of the email. He simply says that in July 2019 the PlacePicker will be removed from their libraries as they have updated them. But currently it is still possible to use it (until July) using the new "compat" library.
Also, I downloaded and tested the app the first days of February, so what you said does not make sense.

**Comment by amuramoto** [comment] 2019-03-17 01:38
Checking back in on this... Can anyone provide an error log? Also, check that you are calling StartActivityForResult rather than StartActivity

**Comment by amuramoto** [comment] 2019-03-30 00:14
Closing since we can't replicate and haven't received any error logs

**Closed by amuramoto** 2019-03-30 00:14 UTC

**Comment by wzywzy19** [comment] 2019-04-07 03:26
The problem still exist

**Comment by venkateshtata** [comment] 2019-05-13 09:30
> With the new SDK, the PlacePicker will only work for API keys that were activated prior to the PlacePicker's deprecation date (January 29, 2019). Or, at least, that's how I interpret the email Google sent me when they announced the new SDK:
> 
> > Effective January 29, 2019, the upgraded Places SDKs for Android and iOS will replace the existing versions of the Places SDKs - please read our documentation for more information. The existing Places SDKs (including the Place Picker feature) can continue being used by current customers of these SDKs until July 29, 2019. In order to avoid service disruption, please start using the upgraded SDK versions before July 29, 2019.
> 
> So the PlacePicker might not be working for some people while other features do, simply because your API key isn't flagged to use the PlacePicker through the deprecation period.

@gavingt You're right ! it worked for me when i tried with my previous API Key of my old Google Developer account. Hope there's a market place for old Google API Keys  : )

**Comment by jayrhalani** [comment] 2019-06-05 14:36
It may be because of the older version of the places library is deprecated. 
Check out the [documentation].(https://developers.google.com/places/android-sdk/client-migration)

**Comment by jayrhalani** [comment] 2019-06-05 14:36
It may be because of the older version of the places library is deprecated. 
Check out the [documentation](https://developers.google.com/places/android-sdk/client-migration).

**Comment by alexismo** [comment] 2019-12-29 17:07
I'm trying to complete the Udacity Advanced Android App Development course and running into the same issue.
https://developers.google.com/places/android-sdk/client-migration#place-picker-deprecation says that 

> The Place Picker was deprecated on January 29, 2019. It was turned off on July 29, 2019, and is no longer available. Continued use will result in an error message. The new SDK does not support the Place Picker.

Cross-posting to https://stackoverflow.com/questions/30067210/android-place-picker-closes-immediately-after-launch

**Comment by zawawimanja** [comment] 2020-03-07 18:18
any solution ?? already follow stackover that need to enable places api in cloud console.

**Comment by gavingt** [comment] 2020-03-07 21:48
> any solution ?? already follow stackover that need to enable places api in cloud console.

You can't use PlacePicker any more. It's been turned off. It's gone forever.
